"""Tests for sermon export to Word and PDF formats.

These tests verify the export functionality generates valid documents
with correct content from sermon data.
Tests are written first (TDD) - implementation does not exist yet.
All tests use REAL file generation to temp directories - NO MOCKS.
"""
import pytest
import tempfile
import os


class TestExportToWord:
    """Test suite for Word document export."""

    def test_should_generate_docx_when_valid_sermon_provided(self):
        """Test that Word document is generated from sermon data."""
        from export import export_to_word

        sermon = {
            'title': 'Test Sermon',
            'scripture': 'John 3:16',
            'manuscript': 'This is the sermon content.'
        }

        result = export_to_word(sermon)

        assert result is not None
        assert len(result) > 0  # Should have content

    def test_should_return_bytes_when_export_called(self):
        """Test that export returns bytes."""
        from export import export_to_word

        sermon = {
            'title': 'Test Sermon',
            'scripture': 'John 3:16',
            'manuscript': 'Content here.'
        }

        result = export_to_word(sermon)

        assert isinstance(result, bytes)

    def test_should_create_valid_docx_file(self):
        """Test that generated bytes form a valid .docx file."""
        from export import export_to_word
        from docx import Document
        import io

        sermon = {
            'title': 'Test Sermon',
            'scripture': 'John 3:16',
            'manuscript': 'This is the manuscript content.'
        }

        result = export_to_word(sermon)

        # Should be readable as a Word document
        doc = Document(io.BytesIO(result))
        assert doc is not None

    def test_should_include_title_in_word_document(self):
        """Test that sermon title appears in document."""
        from export import export_to_word
        from docx import Document
        import io

        sermon = {
            'title': 'Grace and Truth',
            'scripture': 'John 3:16',
            'manuscript': 'Content.'
        }

        result = export_to_word(sermon)
        doc = Document(io.BytesIO(result))

        # Extract all text from document
        full_text = '\n'.join([para.text for para in doc.paragraphs])

        assert 'Grace and Truth' in full_text

    def test_should_include_scripture_in_word_document(self):
        """Test that scripture reference appears in document."""
        from export import export_to_word
        from docx import Document
        import io

        sermon = {
            'title': 'Test Sermon',
            'scripture': 'Romans 8:28',
            'manuscript': 'Content.'
        }

        result = export_to_word(sermon)
        doc = Document(io.BytesIO(result))

        full_text = '\n'.join([para.text for para in doc.paragraphs])

        assert 'Romans 8:28' in full_text

    def test_should_include_manuscript_in_word_document(self):
        """Test that manuscript content appears in document."""
        from export import export_to_word
        from docx import Document
        import io

        sermon = {
            'title': 'Test Sermon',
            'scripture': 'John 3:16',
            'manuscript': 'This is the full manuscript text that should appear in the exported document.'
        }

        result = export_to_word(sermon)
        doc = Document(io.BytesIO(result))

        full_text = '\n'.join([para.text for para in doc.paragraphs])

        assert 'full manuscript text' in full_text

    def test_should_include_outline_when_available(self):
        """Test that outline is included if provided."""
        from export import export_to_word
        from docx import Document
        import io

        sermon = {
            'title': 'Test Sermon',
            'scripture': 'John 3:16',
            'manuscript': 'Content.',
            'outline': '1. First Point\n2. Second Point\n3. Third Point'
        }

        result = export_to_word(sermon)
        doc = Document(io.BytesIO(result))

        full_text = '\n'.join([para.text for para in doc.paragraphs])

        assert 'First Point' in full_text
        assert 'Second Point' in full_text

    def test_should_handle_missing_manuscript_gracefully(self):
        """Test that export works with missing manuscript."""
        from export import export_to_word

        sermon = {
            'title': 'Test Sermon',
            'scripture': 'John 3:16'
            # No manuscript
        }

        result = export_to_word(sermon)

        # Should still generate a document
        assert result is not None
        assert len(result) > 0

    def test_should_handle_large_manuscript(self):
        """Test export with 2000+ word manuscript."""
        from export import export_to_word
        from docx import Document
        import io

        # Generate a large manuscript
        large_text = ' '.join(['word'] * 2500)

        sermon = {
            'title': 'Large Sermon',
            'scripture': 'John 3:16',
            'manuscript': large_text
        }

        result = export_to_word(sermon)
        doc = Document(io.BytesIO(result))

        # Should contain the large text
        full_text = '\n'.join([para.text for para in doc.paragraphs])
        assert 'word' in full_text


class TestExportToPDF:
    """Test suite for PDF export."""

    def test_should_generate_pdf_when_valid_sermon_provided(self):
        """Test that PDF is generated from sermon data."""
        from export import export_to_pdf

        sermon = {
            'title': 'Test Sermon',
            'scripture': 'John 3:16',
            'manuscript': 'This is the sermon content.'
        }

        result = export_to_pdf(sermon)

        assert result is not None
        assert len(result) > 0

    def test_should_return_bytes_when_pdf_export_called(self):
        """Test that PDF export returns bytes."""
        from export import export_to_pdf

        sermon = {
            'title': 'Test Sermon',
            'scripture': 'John 3:16',
            'manuscript': 'Content here.'
        }

        result = export_to_pdf(sermon)

        assert isinstance(result, bytes)

    def test_should_start_with_pdf_magic_bytes(self):
        """Test that generated file is valid PDF format."""
        from export import export_to_pdf

        sermon = {
            'title': 'Test Sermon',
            'scripture': 'John 3:16',
            'manuscript': 'Content.'
        }

        result = export_to_pdf(sermon)

        # PDF files start with %PDF-
        assert result.startswith(b'%PDF-')

    def test_should_include_title_in_pdf(self):
        """Test that sermon title appears in PDF."""
        from export import export_to_pdf

        sermon = {
            'title': 'Amazing Grace Sermon',
            'scripture': 'John 3:16',
            'manuscript': 'Content.'
        }

        result = export_to_pdf(sermon)

        # Title should be in the PDF content somewhere
        # PDF is binary so we check for the bytes
        assert b'Amazing Grace' in result or 'Amazing Grace' in result.decode('latin-1', errors='ignore')

    def test_should_handle_missing_fields_in_pdf(self):
        """Test that PDF export handles missing optional fields."""
        from export import export_to_pdf

        sermon = {
            'title': 'Minimal Sermon',
            'scripture': 'John 3:16'
            # No manuscript, no outline
        }

        result = export_to_pdf(sermon)

        assert result is not None
        assert result.startswith(b'%PDF-')

    def test_should_handle_large_manuscript_in_pdf(self):
        """Test PDF export with 2000+ word manuscript."""
        from export import export_to_pdf

        large_text = 'Lorem ipsum dolor sit amet. ' * 300  # ~1800 words

        sermon = {
            'title': 'Large Sermon',
            'scripture': 'John 3:16',
            'manuscript': large_text
        }

        result = export_to_pdf(sermon)

        assert result is not None
        assert len(result) > 1000  # Should be substantial


class TestExportRoutes:
    """Test suite for Flask export routes."""

    def test_should_return_200_when_word_export_requested(self):
        """Test that Word export route returns 200."""
        from app import create_app
        from database import init_db, get_db

        app = create_app({'TESTING': True, 'DATABASE': ':memory:'})

        with app.app_context():
            conn = get_db()
            init_db(conn)
            cursor = conn.cursor()
            cursor.execute(
                "INSERT INTO sermons (title, scripture, manuscript) VALUES (?, ?, ?)",
                ('Test Sermon', 'John 3:16', 'Content')
            )
            conn.commit()
            sermon_id = cursor.lastrowid

        with app.test_client() as client:
            response = client.get(f'/sermon/{sermon_id}/export/word')

            assert response.status_code == 200

    def test_should_return_docx_content_type_for_word_export(self):
        """Test that Word export returns correct content-type."""
        from app import create_app
        from database import init_db, get_db

        app = create_app({'TESTING': True, 'DATABASE': ':memory:'})

        with app.app_context():
            conn = get_db()
            init_db(conn)
            cursor = conn.cursor()
            cursor.execute(
                "INSERT INTO sermons (title, scripture, manuscript) VALUES (?, ?, ?)",
                ('Test Sermon', 'John 3:16', 'Content')
            )
            conn.commit()
            sermon_id = cursor.lastrowid

        with app.test_client() as client:
            response = client.get(f'/sermon/{sermon_id}/export/word')

            assert 'application/vnd.openxmlformats-officedocument.wordprocessingml.document' in response.content_type

    def test_should_return_200_when_pdf_export_requested(self):
        """Test that PDF export route returns 200."""
        from app import create_app
        from database import init_db, get_db

        app = create_app({'TESTING': True, 'DATABASE': ':memory:'})

        with app.app_context():
            conn = get_db()
            init_db(conn)
            cursor = conn.cursor()
            cursor.execute(
                "INSERT INTO sermons (title, scripture, manuscript) VALUES (?, ?, ?)",
                ('Test Sermon', 'John 3:16', 'Content')
            )
            conn.commit()
            sermon_id = cursor.lastrowid

        with app.test_client() as client:
            response = client.get(f'/sermon/{sermon_id}/export/pdf')

            assert response.status_code == 200

    def test_should_return_pdf_content_type_for_pdf_export(self):
        """Test that PDF export returns correct content-type."""
        from app import create_app
        from database import init_db, get_db

        app = create_app({'TESTING': True, 'DATABASE': ':memory:'})

        with app.app_context():
            conn = get_db()
            init_db(conn)
            cursor = conn.cursor()
            cursor.execute(
                "INSERT INTO sermons (title, scripture, manuscript) VALUES (?, ?, ?)",
                ('Test Sermon', 'John 3:16', 'Content')
            )
            conn.commit()
            sermon_id = cursor.lastrowid

        with app.test_client() as client:
            response = client.get(f'/sermon/{sermon_id}/export/pdf')

            assert 'application/pdf' in response.content_type

    def test_should_return_404_when_exporting_nonexistent_sermon(self):
        """Test that exporting missing sermon returns 404."""
        from app import create_app
        from database import init_db, get_db

        app = create_app({'TESTING': True, 'DATABASE': ':memory:'})

        with app.app_context():
            conn = get_db()
            init_db(conn)

        with app.test_client() as client:
            response = client.get('/sermon/99999/export/word')

            assert response.status_code == 404

    def test_should_include_content_disposition_header(self):
        """Test that download filename is set correctly."""
        from app import create_app
        from database import init_db, get_db

        app = create_app({'TESTING': True, 'DATABASE': ':memory:'})

        with app.app_context():
            conn = get_db()
            init_db(conn)
            cursor = conn.cursor()
            cursor.execute(
                "INSERT INTO sermons (title, scripture, manuscript) VALUES (?, ?, ?)",
                ('My Test Sermon', 'John 3:16', 'Content')
            )
            conn.commit()
            sermon_id = cursor.lastrowid

        with app.test_client() as client:
            response = client.get(f'/sermon/{sermon_id}/export/word')

            # Should have Content-Disposition header with filename
            assert 'Content-Disposition' in response.headers
            assert 'attachment' in response.headers['Content-Disposition']


class TestExportFileWriting:
    """Test suite for writing exports to temp files."""

    def test_should_write_valid_docx_to_file(self):
        """Test writing Word export to actual file."""
        from export import export_to_word
        from docx import Document

        sermon = {
            'title': 'File Test Sermon',
            'scripture': 'John 3:16',
            'manuscript': 'This is the content.'
        }

        result = export_to_word(sermon)

        with tempfile.NamedTemporaryFile(suffix='.docx', delete=False) as f:
            f.write(result)
            temp_path = f.name

        try:
            # Should be able to open the file
            doc = Document(temp_path)
            assert doc is not None
        finally:
            os.unlink(temp_path)

    def test_should_write_valid_pdf_to_file(self):
        """Test writing PDF export to actual file."""
        from export import export_to_pdf

        sermon = {
            'title': 'PDF File Test',
            'scripture': 'John 3:16',
            'manuscript': 'This is the content.'
        }

        result = export_to_pdf(sermon)

        with tempfile.NamedTemporaryFile(suffix='.pdf', delete=False) as f:
            f.write(result)
            temp_path = f.name

        try:
            # File should exist and have content
            assert os.path.exists(temp_path)
            assert os.path.getsize(temp_path) > 0

            # Should start with PDF magic bytes
            with open(temp_path, 'rb') as f:
                header = f.read(5)
                assert header == b'%PDF-'
        finally:
            os.unlink(temp_path)


class TestExportFormatting:
    """Test suite for document formatting."""

    def test_should_preserve_paragraph_breaks_in_word(self):
        """Test that paragraph breaks are preserved in Word export."""
        from export import export_to_word
        from docx import Document
        import io

        sermon = {
            'title': 'Test Sermon',
            'scripture': 'John 3:16',
            'manuscript': 'First paragraph.\n\nSecond paragraph.\n\nThird paragraph.'
        }

        result = export_to_word(sermon)
        doc = Document(io.BytesIO(result))

        # Should have multiple paragraphs
        paragraphs = [p.text for p in doc.paragraphs if p.text.strip()]
        assert len(paragraphs) >= 3

    def test_should_handle_special_characters_in_word(self):
        """Test that special characters are handled correctly."""
        from export import export_to_word
        from docx import Document
        import io

        sermon = {
            'title': 'Test with "Quotes" & Symbols',
            'scripture': 'John 3:16',
            'manuscript': "Content with em-dash — and curly 'quotes' and apostrophe's."
        }

        result = export_to_word(sermon)
        doc = Document(io.BytesIO(result))

        # Should not throw errors and contain some of the special chars
        full_text = '\n'.join([para.text for para in doc.paragraphs])
        assert 'Quotes' in full_text or 'quotes' in full_text
